version: '3'

services:
  cmd_service:
    container_name: my-cmd
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - my-cmd-network

networks:
  my-cmd-network:
    driver: bridge